fixes #issuenumber117
google/gcp_scanner pull request #127
Opened 2023-03-31 08:20 UTC by NEGRAH-S

## Description

[Provide a brief description of the changes you have made and why they are necessary.]

## Changes Made
[List the changes you have made in bullet points.]

## Checklist
- [ ] I have read and followed the contributing guidelines.
- [ ] I have tested my changes thoroughly and they work as expected.
- [ ] I have added necessary tests for the changes made.
- [ ] I have updated the documentation to reflect the changes made.
- [ ] My code follows the project's coding style and standards.
- [ ] I have added appropriate commit messages and comments for my changes.

## Related Issues
[If your changes relate to any existing issues, please list them here.]

## Additional Notes
[Provide any additional notes or context that may be helpful for the reviewers.]

Feel free to modify and customize this template as needed to fit the specific needs of the GCP Scanner project.

2023-03-31 14:23 UTC, mshudrak commented
Please accept Google CLA before I can review this commit. Adjust commit message to better summarize what you want to change in this PR.

2023-04-05 17:58 UTC, Bhardwaj-Himanshu commented
Hi @NEGRAH-S, if you are still unable to figure out why Google-CLA is stopping you from making a change.

Ensure both of your Github-account- @NEGRAH-S and your Local-Git-Machine account-<ne***h​@Negrahs-MacBook-Pro.local> are linked with a single Email account.

Also all the commits should be made after first [switching your github email to public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address) and then use ```git config --global user.email "MY_NAME@example.com"``` to configure your local repoistory's Email Address.

I hope this helps, cause I just figured it out recently too!
Thanks

2023-04-06 10:05 UTC, ZetaTwo requested changes
It's very difficult to follow what changes are where and why. Please squash the commits and separate the whitespace changes from the comment changes so that I can continue the review.

2023-04-06 10:05 UTC, ZetaTwo commented on scanner.py
> +'''!/usr/bin/env python3
This whole block is incorrect. Please revert

2023-04-06 10:05 UTC, ZetaTwo commented on src/gcp_scanner/__init__.py
> +#It is a empty file as of now.
Remove comment

2023-04-06 10:05 UTC, ZetaTwo commented on src/gcp_scanner/__main__.py
> +# imprted main module of GCP
Redundant comment

2023-04-06 10:05 UTC, ZetaTwo commented on src/gcp_scanner/__main__.py
> +if __name__ == "__main__":
Why " instead of '?

2023-04-06 10:05 UTC, ZetaTwo commented on src/gcp_scanner/arguments.py
> +# Defined a function using imported module
Redundant comment

2023-04-07 11:58 UTC, NEGRAH-S commented
> Please accept Google CLA before I can review this commit. Adjust commit message to better summarize what you want to change in this PR.

mam i have accepten it but don't know why it is showing like that let me check the linked email for both

2023-04-08 17:08 UTC, Bhardwaj-Himanshu commented
Hi @NEGRAH-S, Hope you are doing well mate!
If you are still facing the issue of not being able to fix the "Verification by Google-CLA" issue, I would be happy to help you over that.

2023-04-10 14:06 UTC, NEGRAH-S commented
@Bhardwaj-Himanshu  hey bro, yeah I would highly admire if you could help in same.

2023-04-11 02:07 UTC, Bhardwaj-Himanshu commented
@NEGRAH-S, I am very happy to help brother!
But first I would be require some help from your side.
Could you please share your github email id: the one you use to sign in.
and the share me the information which appears in terminal after typing `git config --list`

Thanks

2023-04-11 13:34 UTC, NEGRAH-S commented
@Bhardwaj-Himanshu  
My GitHub email- negrahsingh32@gmail.com 
other credential as per my terminal :
<img width="476" alt="Screenshot 2023-04-11 at 7 00 46 PM" src="https://user-images.githubusercontent.com/86295105/231178748-986f70c6-3bde-48eb-93b4-26155862aad2.png">

2023-04-11 16:28 UTC, Bhardwaj-Himanshu commented
Hi @NEGRAH-S,
Thanks for the images,
Go to github settings now-->emails-->"set my email address to private"(below primary email address options)--> set this either to public.

OR

You can change your "GIT-CONFIG USEREMAIL <to your private id as shown on github>"

This link is a detailed guide, please do check it out-https://help.umbler.com/hc/en-us/articles/360007180671-Turning-your-e-mail-public-on-GitHub

2023-04-12 13:43 UTC, NEGRAH-S commented
@Bhardwaj-Himanshu  I did as u said then also updated my CLA details it shows updated but still issue is not resolved. can we connect on some  private medium for solve the issue. 
<img width="1101" alt="Screenshot 2023-04-12 at 7 12 40 PM" src="https://user-images.githubusercontent.com/86295105/231476533-9c8f8e46-3779-4a76-8b47-c86fb3fef634.png">

2023-04-12 15:41 UTC, Bhardwaj-Himanshu commented
@NEGRAH-S, Thanks for the feedback.

Now that you have updated your email both on your local machine and github--> I want you to check if your email is marked **private or public** on github, using the link- https://help.umbler.com/hc/en-us/articles/360007180671-Turning-your-e-mail-public-on-GitHub

Coming on to connecting privately, I would love to do so, so here is my linkedin-https://www.linkedin.com/in/himanshu--bhardwaj/

But let's keep this discussion open and public here on github, so that if I am unable to help, others can look into it and help you.

After opting for public email id on github, I want you to again commit the changes first by making a small change on your local machine, and then upload them into github into another branch or `trying using same branch even #117` for your forked repository.

Then let the checks take place and let me know via a screenshot what happens!

2023-04-17 13:48 UTC, NEGRAH-S commented
As discussed with @Bhardwaj-Himanshu  I have decided to close this PR and make new with changes mentioned by @ZetaTwo .

2023-04-17 14:22 UTC, Bhardwaj-Himanshu commented
@mshudrak, He'll open this pull request again, please don't close this until now.
@NEGRAH-S, do link this issue, while create a new PR.

2023-04-18 12:33 UTC, NEGRAH-S commented
> @mshudrak, He'll open this pull request again, please don't close this until now.
> @NEGRAH-S, do link this issue, while create a new PR.

okh bro I got that will link the issue to my new PR this time.

2023-04-18 12:47 UTC, Bhardwaj-Himanshu commented
Also, before changing the lines could you please add `"editor.formatOnSaveMode": "modifications",`--this line of code to your settings.json file?
What would it do?
-prevent unnecessary introduction of white spaces and blank lines and would only show actual lines modified while doing a commit.
-To do this do **Ctrl+Shift+P in vscode --> settings.json in the commmand palette which appears--> open it--> add `"editor.formatOnSaveMode": "modifications"`--> save**

OR you could watch this youtube video for the same, https://www.youtube.com/watch?v=-7t0ewz7-jk

2023-05-03 01:20 UTC, Bhardwaj-Himanshu commented on src/gcp_scanner/arguments.py
> +    )
Could you also try removing the unnecessary whitespaces and indentations, these create a great amount of confusion when reviewing the file and some changes could go unnoticed.

Thanks!

2023-05-07 14:55 UTC, Bhardwaj-Himanshu commented
@NEGRAH-S Do update this issue with your progress.

Or else @mshudrak @ZetaTwo please close this issue as it's unattended!

2023-05-08 14:21 UTC, NEGRAH-S commented
> @NEGRAH-S Do update this issue with your progress.
> 
> Or else @mshudrak @ZetaTwo please close this issue as it's unattended!

hello @Bhardwaj-Himanshu  , I was occupied with some work but I saw someone has made an PR addressing same issue , so I feel this PR can be closed .

2023-05-08 14:21 UTC, closed without merging