Fix: Output Appending Issue for Each Scan on a Single Project
google/gcp_scanner pull request #128
Opened 2023-03-31 17:40 UTC by Am0stafa

Description:

This PR addresses issue #79, where the output of multiple scans on a single project was appended to the same JSON file. The changes introduced in this PR ensure that a unique file is created for each scan, preventing the output of different scans from being appended to the same file.

Key Changes:

- [x] Added a new `generate_unique_filename` function that generates a unique file name within the output directory by appending a counter to the base name if a file with the same name already exists. This function is essential in preventing the overwriting or appending of previous scan results, as it ensures that each new scan will be saved in a separate file with a unique name.

- [x] Updated the `crawl_loop` function in `src/gcp_scanner/scanner.py` to use the `generate_unique_filename` function when saving the output of the scan. This ensures that a new, unique file is created for each scan, rather than appending the output to an existing file.

By implementing these changes, the output of each scan is now saved in a separate file, eliminating the issue of appending scan results to the same file. This makes it easier for users to analyze the output of individual scans and prevents the unintentional merging of scan results. The `generate_unique_filename` function plays a crucial role in ensuring that each scan's output is saved in a distinct file, which ultimately enhances the usability and reliability of the GCP resource scanner.

## Related Issues
fixes #79

2023-03-31 17:50 UTC, Am0stafa commented
> we have #84 already addressing this problem.
Thank you for pointing this out. I understand that there is already an ongoing PR (#84) that addresses the same issue. My approach offers an alternative solution to the problem, and I'm aware that the existing PR might be outdated and result in conflicts.

Considering the lack of response from the author of the old PR, I would like to propose my solution for your review. If you find it beneficial or more suitable for the project, I am willing to work on integrating the changes. If you think this PR should be closed, that is fine as well.

Please let me know your thoughts and how you would like to proceed with this matter.

2023-03-31 17:51 UTC, Am0stafa commented
> we have #84 already addressing this problem.

Thank you for pointing this out. I understand that there is already an ongoing PR (#84) that addresses the same issue. My approach offers an alternative solution to the problem, and I'm aware that the existing PR might be outdated and result in conflicts.

Considering the lack of response from the author of the old PR, I would like to propose my solution for your review. If you find it beneficial or more suitable for the project, I am willing to work on integrating the changes. If you think this PR should be closed, that is fine as well.

Please let me know your thoughts and how you would like to proceed with this matter.

2023-04-06 09:57 UTC, ZetaTwo requested changes

2023-04-06 09:57 UTC, ZetaTwo commented on src/gcp_scanner/scanner.py
> +      with open(output_file_path, 'a', encoding='utf-8') as outfile:
Same feedback as for the other PR: change to mode "x" to avoid race conditions and move the file creation to early in the execution.

2023-04-07 13:40 UTC, mshudrak commented
There is #84 that's almost ready for merge. I'd close this PR.

2023-04-10 13:47 UTC, mshudrak commented
#84 has been merged. Closing this one.

2023-04-10 13:47 UTC, closed without merging