feat: Extend parser to parse most of resources
google/gcp_scanner pull request #262
Opened 2023-07-31 17:15 UTC by yahia3200

## Description

Change parser implementation to a more generic one that can parse most resources types

![image](https://github.com/google/gcp_scanner/assets/30212455/7b53851f-a208-4781-b062-5bb14ce36485)

## Additional Notes

The types supported by the tool are:
- `Compute Instance`
- `Compute Disk`
- `Compute Image`
- `Machine Image`
- `Compute Snapshot`
- `Managed Zone`
- `SQL Instance`
- `Cloud Function`
- `Dns Policies`
- `Pubsub Sub`

These types are defined in  `availableResourceTypes` in `src/types/resources.ts` 
Other types have special structures in the output file which we can handle later

2023-07-31 22:55 UTC, mshudrak requested changes
Overall looks good. I left two minor comments. By the way, when I test it and click on `Detail` button it does not show details. I do it on a full log that was created a while ago. Is it expected?

2023-07-31 22:55 UTC, mshudrak commented on visualization_tool/src/types/resources.ts
> +  'Dns Policie',
Dns Policy or Policies

2023-07-31 22:55 UTC, mshudrak commented on visualization_tool/src/components/ResourcesList/utils.ts
> +      return MangedZone;
ManagedZone

2023-08-01 10:35 UTC, yahia3200 commented on visualization_tool/src/components/ResourcesList/utils.ts
> +      return MangedZone;
Done

2023-08-01 10:35 UTC, yahia3200 commented on visualization_tool/src/types/resources.ts
> +  'Dns Policie',
Done

2023-08-01 10:35 UTC, yahia3200 commented
Yes because I didn't add the Details sections to this branch yet

2023-08-01 16:10 UTC, mshudrak approved these changes

2023-08-01 16:11 UTC, mshudrak commented
There is one small typo but other than good to merge.

2023-08-01 16:34 UTC, yahia3200 commented on visualization_tool/src/components/ControlMenu/Controller.ts
> +      if (type === 'Dns Policie') type = 'Dns Policy';
To get the type of the resource, I use the name of it in the json file, then remove the last character to make it singular 
This doesn't work in the naming of `dns_policies` so I handle it differently using this if statement

2023-08-01 17:46 UTC, mshudrak commented on visualization_tool/src/components/ControlMenu/Controller.ts
> +      if (type === 'Dns Policie') type = 'Dns Policy';
Why do you need to remove the last character?

2023-08-01 18:15 UTC, yahia3200 commented on visualization_tool/src/components/ControlMenu/Controller.ts
> +      if (type === 'Dns Policie') type = 'Dns Policy';
Because I used the singular names of resources in the code 
I can change that to use plural ones

2023-08-01 18:28 UTC, mshudrak commented on visualization_tool/src/components/ControlMenu/Controller.ts
> +      if (type === 'Dns Policie') type = 'Dns Policy';
all good. merging it.

2023-08-01 18:28 UTC, merged