docs: Add visualization tool usage in readme
google/gcp_scanner pull request #281
Opened 2023-09-04 21:25 UTC by yahia3200

## Description

Visualization tool usage documentation

## Changes Made
- Update the readme file to mention the visualization tool 
- Add a usage file to describe how to use the tool

2023-09-04 21:39 UTC, ZetaTwo requested changes
Could you try to see if you can make the animations .webp files instead of .gif to improve both file size and image quality?

2023-09-04 21:39 UTC, ZetaTwo commented on misc/visualization_tool_images/.gif
What is this file?

2023-09-05 13:07 UTC, yahia3200 commented
> Could you try to see if you can make the animations .webp files instead of .gif to improve both file size and image quality?

OK, I will try to

2023-09-05 13:08 UTC, yahia3200 commented on misc/visualization_tool_images/.gif
It is a wrong file, I will delete it

2023-09-05 22:09 UTC, yahia3200 commented on misc/visualization_tool_images/.gif
Done

2023-09-05 22:14 UTC, yahia3200 commented
I found that GitHub can't render webp images 
https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files
Do you suggest to try find some hacks around it or leave it for now?

2023-09-06 19:39 UTC, ZetaTwo commented
That list is not exhaustive, see https://github.com/TomasHubelbauer/markdown-webp for a working example (code: https://github.com/TomasHubelbauer/markdown-webp/blob/main/readme.md?plain=1) so it really should work.

2023-09-07 10:31 UTC, yahia3200 commented
It wasn't working on my vscode preview which made me search if it was supported. I tried again and it turns out that I only need to refresh the preview 😅​

2023-09-07 11:09 UTC, ZetaTwo approved these changes

2023-09-07 11:09 UTC, merged

2023-09-07 11:09 UTC, ZetaTwo commented
Really nice work!