Update README.md
google/gcp_scanner pull request #313
Opened 2023-12-29 06:20 UTC by unibik

added setup process of tool

## Description

[Provide a brief description of the changes you have made and why they are necessary.]

## Changes Made
[List the changes you have made in bullet points.]

## Checklist
- [ ] I have read and followed the contributing guidelines.
- [ ] I have tested my changes thoroughly and they work as expected.
- [ ] I have added necessary tests for the changes made.
- [ ] I have updated the documentation to reflect the changes made.
- [ ] My code follows the project's coding style and standards.
- [ ] I have added appropriate commit messages and comments for my changes.

## Related Issues
[If your changes relate to any existing issues, please list them here.]

## Additional Notes
[Provide any additional notes or context that may be helpful for the reviewers.]

Feel free to modify and customize this template as needed to fit the specific needs of the GCP Scanner project.

2024-01-24 19:19 UTC, mshudrak requested changes
Left some suggestions.

2024-01-24 19:19 UTC, mshudrak commented on README.md
> +### Setup of tool(gcp_scanner)
Hey, thanks for the commit. We already have instruction on how to use the tool in INSTALL.MD. Could you check with that doc and add these instructions there? We can also reference INSTALL.md from here.

2024-02-15 13:29 UTC, HasanZaigam commented
please assign me this problem

2024-02-15 17:31 UTC, mshudrak commented
We do not assign problem, feel free to just submit PR.

2024-02-16 16:33 UTC, mshudrak commented
No activity, closing the bug.

2024-02-16 16:33 UTC, closed without merging