Replace print() statements with logging.info() calls for better logging
google/gcp_scanner pull request #81
Opened 2023-03-06 22:59 UTC by Am0stafa

## Description
Use logging.info() instead of print() statements for more flexible logging

## Motivation and Context
Logging is a more flexible and customizable way to display information in the project, as compared to using `print()` statements and you can easily switch between different log levels, such as debug, info, warning, error, and critical by specifying using -l argument.

## How to Test
This change should not affect the functionality of the project. To test, simply run the project and verify that the expected log messages are displayed in the console or log file.

## Related Issues
None.

## Type of Change
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Checklist
- [x] I have tested this change thoroughly.
- [x] I have added appropriate comments to the code for future reference.
- [x] I have updated the documentation (if applicable).

2023-03-06 23:03 UTC, ZetaTwo requested changes
Overall fine. Just need to replace f-strings with the interpolation provided by the log library.

I also wonder if we should set up logging more properly and create a log object with settings set on it but that is a separate issue.

2023-03-06 23:03 UTC, ZetaTwo commented on src/gcp_scanner/credsdb.py
> +    logging.info(f"Scanning {dir_path} for credentials.db")
For log calls, don't use f-strings, instead do `logging.info("Scanning %s for credentials.db", dir_path)`

2023-03-06 23:03 UTC, ZetaTwo commented on src/gcp_scanner/credsdb.py
> +      logging.info(f"Identified accessible gcloud config profile {full_path}")
For log calls, don't use f-strings.

2023-03-06 23:03 UTC, ZetaTwo commented on src/gcp_scanner/credsdb.py
> +  logging.info(f"Identified {len(list_of_creds_files)} credential DBs")
For log calls, don't use f-strings.

2023-03-06 23:03 UTC, ZetaTwo commented on src/gcp_scanner/credsdb.py
> +  logging.info(f"Identified {len(res)} credential entries")
For log calls, don't use f-strings.

2023-03-06 23:03 UTC, ZetaTwo commented on src/gcp_scanner/scanner.py
> +      logging.info(f'Inspecting project {project_id}')
For log calls, don't use f-strings.

2023-03-06 23:19 UTC, Am0stafa commented
@ZetaTwo yeah as I was reading through the logging documentation I thought about that.
what about now i add a configuration to add the logs to a logging file ?

2023-03-07 02:18 UTC, mshudrak commented
Ideally, we need several levels of logging. I left those messages via print on purpose in order to guide user of what's going on during the GCP Scanner run. We need them to be printed by default (without -l INFO) option.

2023-03-07 10:37 UTC, Am0stafa commented
@mshudrak yeah that makes sense but what we can do is make the logging level by default at the information level such that even if the user didn't specify the logging level, the user still would be able to see the logs

2023-03-07 13:49 UTC, mshudrak commented
@Am0stafa yes it can work but now we have too much information in the console from all logging which we don't want to have by default :) I'd suggest at least one more level of logging for those messages that were print().

2023-03-07 16:40 UTC, Am0stafa commented
@mshudrak yeah I get your point I thought that would be a meaningful addition. Now I adjusted the formatting so that the message looks better at the console and is easier to read, along with the ability to disable all logs.

2023-03-07 19:01 UTC, Am0stafa commented
Firstly sorry for all the pylint fixes, it took me a while to understand it and configure it,
Secondly, @mshudrak Do you think I should close this PR if you think it's better to print rather than show all the logging form information levels and below or disable them?

2023-03-08 02:11 UTC, mshudrak commented
@Am0stafa if you can implement additional level of logging in this PR it is fine to keep it.

2023-03-08 10:55 UTC, Am0stafa commented
@mshudrak actually its better if it's a print statement rather than adding another level of logging,
so what I will do is close this PR and make another one where I only change the logging format.

2023-03-08 10:55 UTC, closed without merging