Update CONTRIBUTING.md
google/gcp_scanner pull request #97
Opened 2023-03-13 15:50 UTC by ro4i7

## Description

[Update CONTRIBUTING.md .]

## Changes Made
[i have updated the CONTRIBUTING.md as necessary ]

## Checklist
- [ ] I have read and followed the contributing guidelines.
- [ ] I have tested my changes thoroughly and they work as expected.
- [ ] I have added necessary tests for the changes made.
- [ ] I have updated the documentation to reflect the changes made.
- [ ] My code follows the project's coding style and standards.
- [ ] I have added appropriate commit messages and comments for my changes.

## Related Issues
[If your changes relate to any existing issues, please list them here.]

## Additional Notes
[Provide any additional notes or context that may be helpful for the reviewers.]

Feel free to modify and customize this template as needed to fit the specific needs of the GCP Scanner project.

2023-03-13 15:52 UTC, ro4i7 commented
Hello, @ZetaTwo I have updated. if there is any issue, please tag me. Thank you.

2023-03-13 18:20 UTC, mshudrak commented
Please resolve the conflict. We had quite similar PR recently merged.

2023-03-13 18:23 UTC, ro4i7 commented
> Please resolve the conflict. We had quite similar PR recently merged.

yeah, resolved the conflict. I have done this PR yesterday, but I committed to two solutions in a single PR.

2023-03-13 18:26 UTC, ro4i7 commented
> > Please resolve the conflict. We had quite similar PR recently merged.
> 
> yeah, resolved the conflict. I have done this PR yesterday, but I committed to two solutions in a single PR.

if possible, please merge it to the `main`.

2023-03-13 18:33 UTC, mshudrak requested changes

2023-03-13 18:33 UTC, mshudrak commented on CONTRIBUTING.md
> +
Unnecessary new line

2023-03-13 18:33 UTC, mshudrak commented on CONTRIBUTING.md
> +
Unnecessary new line

2023-03-13 18:33 UTC, mshudrak commented on CONTRIBUTING.md
> +
Unnecessary new line

2023-03-13 18:33 UTC, mshudrak commented on CONTRIBUTING.md
> +
Unnecessary new line

2023-03-13 18:33 UTC, mshudrak commented on CONTRIBUTING.md
> +**Example:** `feat/<issue-id>/gcp-compute-engine-support`
You need to have new line in order to have it as a list and not like a sentence. Additionally, you have duplicate feat/issue-id now. PTAL at the final result.
https://github.com/ro4i7/gcp_scanner/blob/patch1/CONTRIBUTING.md

2023-03-13 18:33 UTC, mshudrak commented on CONTRIBUTING.md
> +
Unnecessary new line

2023-03-14 13:54 UTC, mshudrak requested changes
I am not sure I am following what you want to change with that PR. Are you sure we need that change at all?

2023-03-14 13:54 UTC, mshudrak commented on CONTRIBUTING.md
> +
Why removing that?

2023-03-14 13:54 UTC, mshudrak commented on CONTRIBUTING.md
> +
Unnecessary new line

2023-03-14 13:54 UTC, mshudrak commented on CONTRIBUTING.md
> -- Use descriptive names that reflect the purpose of the branch.
Why removing that?

2023-03-14 13:54 UTC, mshudrak commented on CONTRIBUTING.md
> +Contributions to this project must be accompanied by a Contributor License Agreement. You (or your employer) retain the copyright to your contribution; this simply gives us permission to use and redi
I don't think we need to change the link

2023-03-14 17:37 UTC, ro4i7 commented
> I am not sure I am following what you want to change with that PR. Are you sure we need that change at all?

@mshudrak  Changed, please check.

2023-03-15 14:02 UTC, mshudrak requested changes
Still has some minor issue with text. right now it is

Example: feat//gcp-compute-engine-support.

Please take a look at your final result before submitting PR.

2023-03-15 15:27 UTC, mshudrak approved these changes

2023-03-15 15:28 UTC, mshudrak requested changes
Sorry, approved by mistake. PTAL at my comment.

2023-03-15 15:28 UTC, mshudrak commented on CONTRIBUTING.md
> -- Add `issue tracker id`
We still want this line.

2023-03-15 18:26 UTC, mshudrak approved these changes

2023-03-15 18:28 UTC, mshudrak approved these changes

2023-03-15 18:29 UTC, merged